name: Packer Image VM

on:
  push:
    paths:
      - "packer/**"
    branches:
      - master
  pull_request:
    paths:
      - "packer/**"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Image VM Build with Packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.PACKER_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info

      # validate templates
      - name: Validate Template
        if: github.event_name == 'pull_request'
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only -var 'project=${{ secrets.GCP_PROJECT_ID }}'"
          target: packer/image.pkr.hcl

      # build artifact
      - name: Build Artifact
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var 'project=${{ secrets.GCP_PROJECT_ID }}'"
          target: packer/image.pkr.hcl
      # additional steps to process artifacts
