---
name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          target: packer/image.pkr.hcl

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/image.pkr.hcl

      # build artifact
      - name: Build Artifact
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer/image.pkr.hcl
      # additional steps to process artifacts
